"""initial_schema

Revision ID: 865c159f0ad7
Revises: 
Create Date: 2026-05-29 01:34:17.992006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865c159f0ad7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('favorite_riders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_favorite_riders_customer_rider', 'favorite_riders', ['customer_id', 'rider_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('new_request', 'request_accepted', 'rider_arrived', 'trip_started', 'trip_completed', 'payment_received', 'favourite_rider_online', 'admin_alert', 'request_escalated', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('pricing_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.Enum('ride', 'delivery', name='requesttype'), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('per_km_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('per_minute_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('surge_multiplier', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pricing_config_type_vehicle', 'pricing_config', ['request_type', 'vehicle_type'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('preferred_rider_id', sa.UUID(), nullable=True),
    sa.Column('request_type', sa.Enum('ride', 'delivery', name='requesttype'), nullable=False),
    sa.Column('request_status', sa.Enum('pending', 'searching', 'assigned', 'in_progress', 'completed', 'cancelled', 'admin_escalated', name='requeststatus'), nullable=False),
    sa.Column('pickup_latitude', sa.Float(), nullable=False),
    sa.Column('pickup_longitude', sa.Float(), nullable=False),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('dropoff_latitude', sa.Float(), nullable=False),
    sa.Column('dropoff_longitude', sa.Float(), nullable=False),
    sa.Column('dropoff_address', sa.String(length=500), nullable=False),
    sa.Column('package_description', sa.Text(), nullable=True),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('estimated_fare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_fare', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['preferred_rider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_customer_id'), 'requests', ['customer_id'], unique=False)
    op.create_index('ix_requests_customer_status', 'requests', ['customer_id', 'request_status'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_event_type'), 'system_logs', ['event_type'], unique=False)
    op.create_table('user_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_user_locations_coords', 'user_locations', ['latitude', 'longitude'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('total_trips', sa.Integer(), nullable=False),
    sa.Column('wallet_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('customer', 'rider', 'admin', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_roles_user_role', 'user_roles', ['user_id', 'role'], unique=True)
    op.create_table('billing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=True),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('distance_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('time_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('surge_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('billing_status', sa.Enum('unpaid', 'paid', 'partially_paid', 'waived', name='billingstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('mpesa', 'cash', 'wallet', name='paymentmethod'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_commission_pct', sa.Float(), nullable=False),
    sa.Column('rider_earnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_billing_customer_id'), 'billing', ['customer_id'], unique=False)
    op.create_index('ix_billing_customer_status', 'billing', ['customer_id', 'billing_status'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('ratee_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['ratee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ratings_ratee', 'ratings', ['ratee_id'], unique=False)
    op.create_index(op.f('ix_ratings_request_id'), 'ratings', ['request_id'], unique=False)
    op.create_index('ix_ratings_request_rater', 'ratings', ['request_id', 'rater_id'], unique=True)
    op.create_table('request_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('assignment_status', sa.Enum('pending', 'accepted', 'rejected', 'timeout', name='assignmentstatus'), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('distance_at_assignment_km', sa.Float(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('timeout_task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_request_rider', 'request_assignments', ['request_id', 'rider_id'], unique=False)
    op.create_index(op.f('ix_request_assignments_request_id'), 'request_assignments', ['request_id'], unique=False)
    op.create_index(op.f('ix_request_assignments_rider_id'), 'request_assignments', ['rider_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('billing_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('payment_method', sa.Enum('mpesa', 'cash', 'wallet', name='paymentmethod'), nullable=False),
    sa.Column('transaction_status', sa.Enum('pending', 'processing', 'completed', 'failed', 'refunded', name='transactionstatus'), nullable=False),
    sa.Column('mpesa_checkout_request_id', sa.String(length=255), nullable=True),
    sa.Column('mpesa_merchant_request_id', sa.String(length=255), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=100), nullable=True),
    sa.Column('mpesa_phone', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='0', nullable=False),
    sa.Column('flag', sa.String(length=10), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mpesa_receipt_number')
    )
    op.create_index(op.f('ix_transactions_billing_id'), 'transactions', ['billing_id'], unique=False)
    op.create_index('ix_transactions_billing_status', 'transactions', ['billing_id', 'transaction_status'], unique=False)
    op.create_index(op.f('ix_transactions_mpesa_checkout_request_id'), 'transactions', ['mpesa_checkout_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_mpesa_checkout_request_id'), table_name='transactions')
    op.drop_index('ix_transactions_billing_status', table_name='transactions')
    op.drop_index(op.f('ix_transactions_billing_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_request_assignments_rider_id'), table_name='request_assignments')
    op.drop_index(op.f('ix_request_assignments_request_id'), table_name='request_assignments')
    op.drop_index('ix_assignments_request_rider', table_name='request_assignments')
    op.drop_table('request_assignments')
    op.drop_index('ix_ratings_request_rater', table_name='ratings')
    op.drop_index(op.f('ix_ratings_request_id'), table_name='ratings')
    op.drop_index('ix_ratings_ratee', table_name='ratings')
    op.drop_table('ratings')
    op.drop_index('ix_billing_customer_status', table_name='billing')
    op.drop_index(op.f('ix_billing_customer_id'), table_name='billing')
    op.drop_table('billing')
    op.drop_index('ix_user_roles_user_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_table('user_profiles')
    op.drop_index('ix_user_locations_coords', table_name='user_locations')
    op.drop_table('user_locations')
    op.drop_index(op.f('ix_system_logs_event_type'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index('ix_requests_customer_status', table_name='requests')
    op.drop_index(op.f('ix_requests_customer_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index('ix_pricing_config_type_vehicle', table_name='pricing_config')
    op.drop_table('pricing_config')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_favorite_riders_customer_rider', table_name='favorite_riders')
    op.drop_table('favorite_riders')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
