"""allow_null_rider_id_on_assignment

Revision ID: d72bb3507cda
Revises: 603c7102c876
Create Date: 2026-06-07 17:54:01.804433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72bb3507cda'
down_revision: Union[str, Sequence[str], None] = '603c7102c876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_assignments', 'rider_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_assignments', 'rider_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
